### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by anistark** [intellij-solidity/intellij-solidity#14]
## Comments

```
com.intellij.psi.util.PsiTreeUtil.getStubChildrenOfTypeAsList(Lcom/intellij/psi/PsiElement;Ljava/lang/Class;)Ljava/util/List;
```

## Details:

```
com.intellij.psi.util.PsiTreeUtil.getStubChildrenOfTypeAsList(Lcom/intellij/psi/PsiElement;Ljava/lang/Class;)Ljava/util/List;
java.lang.NoSuchMethodError: com.intellij.psi.util.PsiTreeUtil.getStubChildrenOfTypeAsList(Lcom/intellij/psi/PsiElement;Ljava/lang/Class;)Ljava/util/List;
	at me.serce.solidity.lang.psi.impl.SolContractDefinitionImpl.getStateVariableDeclarationList(SolContractDefinitionImpl.java:67)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations(engine.kt:125)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations(engine.kt:109)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations$default(engine.kt:107)
	at me.serce.solidity.lang.resolve.SolResolver.resolveVarLiteral(engine.kt:45)
	at me.serce.solidity.lang.types.InferenceKt.inferRefType(inference.kt:92)
	at me.serce.solidity.lang.types.InferenceKt.inferExprType(inference.kt:105)
	at me.serce.solidity.lang.types.InferenceKt$type$1$type$1.compute(inference.kt:143)
	at me.serce.solidity.lang.types.InferenceKt$type$1$type$1.compute(inference.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at me.serce.solidity.lang.types.InferenceKt$type$1.compute(inference.kt:142)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at me.serce.solidity.lang.types.InferenceKt.getType(inference.kt:141)
	at me.serce.solidity.lang.resolve.ref.SolFunctionCallReference.multiResolve(SolUserDefinedTypeNameReference.kt:57)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:21)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:14)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:20)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.multiResolve(SolReferenceBase.kt:20)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:34)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:14)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:371)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:348)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:215)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:184)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:252)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:214)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.invoke(GotoDeclarationAction.java:84)
	at com.intellij.codeInsight.actions.CodeInsightAction$1$1.run(CodeInsightAction.java:62)
	at com.intellij.codeInsight.actions.CodeInsightAction$1.run(CodeInsightAction.java:69)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:54)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:40)
	at com.intellij.openapi.keymap.impl.IdeMouseEventDispatcher.dispatchMouseEvent(IdeMouseEventDispatcher.java:249)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.NoSuchMethodError: com.intellij.psi.util.PsiTreeUtil.getStubChildrenOfTypeAsList(Lcom/intellij/psi/PsiElement;Ljava/lang/Class;)Ljava/util/List;
	at me.serce.solidity.lang.psi.impl.SolContractDefinitionImpl.getStateVariableDeclarationList(SolContractDefinitionImpl.java:67)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations(engine.kt:125)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations(engine.kt:109)
	at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations$default(engine.kt:107)
	at me.serce.solidity.lang.resolve.SolResolver.resolveVarLiteral(engine.kt:45)
	at me.serce.solidity.lang.types.InferenceKt.inferRefType(inference.kt:92)
	at me.serce.solidity.lang.types.InferenceKt.inferExprType(inference.kt:105)
	at me.serce.solidity.lang.types.InferenceKt$type$1$type$1.compute(inference.kt:143)
	at me.serce.solidity.lang.types.InferenceKt$type$1$type$1.compute(inference.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at me.serce.solidity.lang.types.InferenceKt$type$1.compute(inference.kt:142)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:136)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:129)
	at me.serce.solidity.lang.types.InferenceKt.getType(inference.kt:141)
	at me.serce.solidity.lang.resolve.ref.SolFunctionCallReference.multiResolve(SolUserDefinedTypeNameReference.kt:57)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:21)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:14)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:20)
	at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.multiResolve(SolReferenceBase.kt:20)
	at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:34)
	at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:14)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:371)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:348)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:215)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:184)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by SerCeMan** [comment]
Hi, @anistark!

Can you provide more information? Which JetBrains IDE and what version do you use?

**Comment by anistark** [comment]
IntelIJ IDEA 15

**Comment by SerCeMan** [comment]
@anistark Thank you again for the report. Maintaining old versions can be a huge burden, so I updated the minimal version requirement to IntelliJ 2016.3.
