### ISSUE TITLE
web3j 3.6.0 issue

### ISSUE THREAD

**Issue by branaway** [intellij-solidity/intellij-solidity#143]
I was hacking around with the source code with the web3j version changed to 3.6.0. 

After installed with IntelliJ-idea 2017.1 version, it reported the following error when I compiled a solidity project

loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.web3j.codegen.SolidityFunctionWrapper.<clinit>(SolidityFunctionWrapper.java:84)
	at me.serce.solidity.ide.interop.Web3jStubGenerator.generate(Web3jStubGenerator.kt:11)
	at me.serce.solidity.ide.run.compile.SolidityCompiler.processModule(SolidityCompiler.kt:93)
	at me.serce.solidity.ide.run.compile.SolidityCompiler.access$processModule(SolidityCompiler.kt:24)
	at me.serce.solidity.ide.run.compile.SolidityCompiler$generate$1.accept(SolidityCompiler.kt:32)
	at me.serce.solidity.ide.run.compile.SolidityCompiler$generate$1.accept(SolidityCompiler.kt:24)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at me.serce.solidity.ide.run.compile.SolidityCompiler.generate(SolidityCompiler.kt:30)
	at me.serce.solidity.ide.run.compile.SolCompileAction$actionPerformed$1.run(SolCompileAction.kt:33)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by branaway** [comment]
Hi @mbolotov  thanks for the response. I changed the version to 3.6.0 in the my fork of the source code to build a copy of the plugin locally. I error was generated when I installed my version of the plugin to IDEA.  I'll check out your idea soon.

**Comment by branaway** [comment]
@mbolotov  it worked very well by excluding the slf4j jar. Thanks!

**Comment by mbolotov** [comment]
solc support was removed from the plugin
