### ISSUE TITLE
The default implementation of method 'getId' is deprecated, you need to override it in 'class me.serce.solidity.ide.run.SolidityConfigurationType$configurationFactory$1'

### ISSUE THREAD

**Issue by apottere** [intellij-solidity/intellij-solidity#272]
Getting this error in `IntelliJ IDEA 2021.3 RC (Ultimate Edition) Build #IU-213.5744.125`, but also in many (all?) previous versions of 2021.3 EAP:

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class me.serce.solidity.ide.run.SolidityConfigurationType$configurationFactory$1'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: me.serce.solidity]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.writeExternal(RunnerAndConfigurationSettingsImpl.kt:267)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.writeScheme(RunnerAndConfigurationSettingsImpl.kt:323)
	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:65)
        [...]
```

As far as I can tell, the plugin functions normally, it just throws this error every few minutes which is irritating.

**Comment by SerCeMan** [comment]
Hey, @apottere! Thank you for the report, I'll take a look 👍
