### ISSUE TITLE
StackOverflowError, SolResolver.resolveTypeNameUsingImports(engine.kt:25)

### ISSUE THREAD

**Issue by SerCeMan** [intellij-solidity/intellij-solidity#43]
https://sentry.io/intellij-solidity/intellij-solidity/issues/434366046/

```
java.lang.StackOverflowError: null
    at com.intellij.openapi.vfs.newvfs.impl.VfsData.getNameByFileId(VfsData.java:178)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findIndex(VirtualDirectoryImpl.java:481)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildInArray(VirtualDirectoryImpl.java:130)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChild(VirtualDirectoryImpl.java:150)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:95)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:399)
    at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:57)
    at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:370)
    at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:376)
    at com.intellij.openapi.vfs.VirtualFile.findFileByRelativePath(VirtualFile.java:376)
    at me.serce.solidity.lang.resolve.ref.SolImportPathReference.singleResolve(SolImportPathReference.kt:16)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase.multiResolve(SolReferenceBase.kt:24)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:21)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:14)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase$multiResolve$1.resolve(SolReferenceBase.kt:20)
    at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:139)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
    at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase.multiResolve(SolReferenceBase.kt:20)
    at com.intellij.psi.PsiPolyVariantReferenceBase.resolve(PsiPolyVariantReferenceBase.java:46)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:34)
    at me.serce.solidity.lang.resolve.ref.SolReferenceBase.resolve(SolReferenceBase.kt:14)
    at me.serce.solidity.lang.resolve.SolResolver.resolveTypeNameUsingImports(engine.kt:23)
    at me.serce.solidity.lang.resolve.SolResolver.resolveTypeNameUsingImports(engine.kt:25)
    at me.serce.solidity.lang.resolve.SolResolver.resolveTypeNameUsingImports(engine.kt:25)
(1019 additional frame(s) were not displayed)
```

**Comment by SerCeMan** [comment]
`SolResolver.resolveTypeNameUsingImports` doesn't exist in the project
