### ISSUE TITLE
KNPE: SolFunctionDefMixin#getParameters

### ISSUE THREAD

**Issue by SerCeMan** [intellij-solidity/intellij-solidity#48]
https://sentry.io/intellij-solidity/intellij-solidity/issues/443091738/

```
KotlinNullPointerException: None
    at me.serce.solidity.lang.psi.impl.SolFunctionDefMixin.getParameters(mixins.kt:76)
    at me.serce.solidity.lang.resolve.SolResolver.lexicalDeclarations(engine.kt:140)
    at me.serce.solidity.lang.resolve.SolResolver.access$lexicalDeclarations(engine.kt:11)
    at me.serce.solidity.lang.resolve.SolResolver$lexicalDeclRec$2.invoke(engine.kt:116)
    at me.serce.solidity.lang.resolve.SolResolver$lexicalDeclRec$2.invoke(engine.kt:11)
...
(39 additional frame(s) were not displayed)

null
```

**Comment by SerCeMan** [comment]
duplicate of #46
