### ISSUE TITLE
MissingResourceException: Can't find bundle for base name messages.QuickFixBundle, locale en_US

### ISSUE THREAD

**Issue by SerCeMan** [intellij-solidity/intellij-solidity#53]
https://sentry.io/intellij-solidity/intellij-solidity/issues/474964113/

```
java.util.MissingResourceException: Can't find bundle for base name messages.QuickFixBundle, locale ru_RU
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
    at com.intellij.codeInsight.daemon.QuickFixBundle.getBundle(QuickFixBundle.java:45)
    at com.intellij.codeInsight.daemon.QuickFixBundle.message(QuickFixBundle.java:39)
    at me.serce.solidity.ide.inspections.fixes.ImportFileFix.showHint(ImportFileFix.kt:29)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.showAddImportHint(ShowAutoImportPass.java:147)
    at com.intellij.codeInsight.daemon.impl.ShowAutoImportPass.addImports(ShowAutoImportPass.java:93)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by SerCeMan** [comment]
![screen shot 2018-03-01 at 10 50 58 am](https://user-images.githubusercontent.com/1780970/36819700-9034f19a-1d3e-11e8-8736-4f2b3689e843.png)

**Comment by SerCeMan** [comment]
Hey, @0v1se! Do you have an idea why this might be happening? I'm going to take a look on the next weekend, but if you have any idea, it might be helpful.

**Comment by 0v1se** [comment]
hey @SerCeMan currently I don't
I'll get back if I find anything

**Comment by 0v1se** [comment]
@SerCeMan possibly it's related to messages I used for "Import" fix. I used IDEA's messages and they can be unavailable for some Intellij installations. (not sure about this)
We can add plugin's own message bundle I think (though I don't know yet how to add message bundles and won't have time this weekend)

**Comment by SerCeMan** [comment]
@0v1se No worries, I think we can make it bullet-proof by just hardcoding messages.

**Comment by morozovsk** [comment]
I have the same problem "Can't find bundle for base name messages.QuickFixBundle, locale ru_RU" but only in pycharm community.
In phpstorm this plugin works without problem.
