### ISSUE TITLE
Exception in SolidityIdeCompiler

### ISSUE THREAD

**Issue by SerCeMan** [intellij-solidity/intellij-solidity#70]
```
kotlin.KotlinNullPointerException
	at me.serce.solidity.ide.run.compile.SolidityIdeCompiler.process(SolidityIdeCompiler.kt:48)
	at com.intellij.compiler.impl.FileProcessingCompilerAdapterTask.execute(FileProcessingCompilerAdapterTask.java:94)
	at com.intellij.compiler.impl.CompileDriver.executeCompileTasks(CompileDriver.java:607)
	at com.intellij.compiler.impl.CompileDriver.lambda$startup$3(CompileDriver.java:440)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mbolotov** [comment]
It's expected to be fixed in #66
